// <auto-generated />
namespace Jabbot.TwitterNotifierSprocket.Migrations
{
    using System.Data.Entity.Migrations;
    using System.Data.Entity.Migrations.Infrastructure;
    
    public sealed partial class addedoccupiedrooms : IMigrationMetadata
    {
        string IMigrationMetadata.Id
        {
            get { return "201112201417447_added-occupied-rooms"; }
        }
        
        string IMigrationMetadata.Source
        {
            get { return null; }
        }
        
        string IMigrationMetadata.Target
        {
            get { return "H4sIAAAAAAAEAOy9B2AcSZYlJi9tynt/SvVK1+B0oQiAYBMk2JBAEOzBiM3mkuwdaUcjKasqgcplVmVdZhZAzO2dvPfee++999577733ujudTif33/8/XGZkAWz2zkrayZ4hgKrIHz9+fB8/Iv7Hv/cffPx7vFuU6WVeN0W1/Oyj3fHOR2m+nFazYnnx2Ufr9nz74KPf4+g3Th6fzhbv0p807fbQjt5cNp99NG/b1aO7d5vpPF9kzXhRTOuqqc7b8bRa3M1m1d29nZ2Du7s7d3MC8RHBStPHr9bLtljk/Af9eVItp/mqXWflF9UsLxv9nL55zVDTF9kib1bZNP/so+9kk0nVjt9cFW2b1y+qtjgv8vr1qq6mb/N2LAA+So/LIiPkXufl+XtiuvMQmH5kcSAsTgnb9vrN9SpnTD776Ksmr/0W1Ob3yq+DD+ijl3W1yuv2+lV+7r13NvsovRu+e7f7sn218x5Q+Oyjs2V7b++j9MW6LLNJSR+cZ2WTf5SuPn30uq3q/PN8mddZm89eZqARzdfZLOchKCkerT69HTUe3t3ZAzXuZstl1WYtTX4P+Q6qmJ8a+OJPg/HrtiaG+ih9VrzLZ8/z5UU7t1h/kb0zn9CvH6VfLQviP3qprde5P0r5e3PvyhY/Z/0/z5pWeHKq1BIEntJ0vCmAUG/WNgM8XaKxD7IxMJ9UVZlny/cGCRyPp21xyQzxgfgB2NmSQOUA8cHgnhYNWgvE9xzp47tOTjdK75fT6XpV5LNXVRXI+W2lWDjrfWX4a/Dj7t7BBn68FUGNJLzKf9E6b1ru9b1w+HCZADN8pyqWuVVgt2SPW08oGacv8jabZW32debz62jk/49oYzaH386a+c/yrG+eKrLvbUYMUIdaumu8X+WrqimIZtedWRQor/PWY2pSDq5LMfRjNstdinRf9qU/BiTQDjcB8zgvBstnzCi9LGXsd4/vis+jHzy+O+AcPf4iW61oKj1nST9JX4undLL9+v1dn4XAuDttIh6Qxdb2RJOVXeSdb6lrwvRZUTctSXo2ycBcJ7NFr9nX5gPTv88OXTl3k2Fa43fnpNzoRAo7dcA6Mj+jkS9IkJkISgJCLeYc6ouvp1mZ1QOu3UlVrhfLTW7iJigdr8sH1vnq9jB7vpQPtffl7eH2fSQfcP/b20OOOks+8GiD28MPPacu1u6b94Pou09dmP53t4fa9aJ8qN3v+lAf3+1weFeyPF2vLTvGsyunt5LiUC9/89I87PVxBzdJ9ebXh2aiLzjvKy0xB66rK7rf3x6675sFXOJ9/v8aDgmM7TfPIINeJMO/iT82vj1E/q7ifz+l/4Vz7nwg3sc/5KnreTXdJrZ3/cT+bb0a9SgCV4fH380D9VwMafJRSkS6LGZwL15fN22+GKPB+PUvKk/KgsbrGnyRLYtzEpk31dscOS3ygL5+3sj65k0zK//fnDwqQIIbA5P3jDKjSZ/lZVZP51m9tcje3XnfoHEgkfNBMIeSMySzOdKR7z3sDcmZSdG+N7hYYuZr4xZPzHxtcPHEzM2jvHUM/3OflDG81U/BvCethnMuH8S+/TzKLWdzaA56c/Bzmkf5WVFMni187xl4v5xGP+QNEbNm07cCQykMsWU0wZOKEBcENenRGW8XbJi96IEPv45100mP3NBdkODo9RZ8G+vsm8iP9D2Gx3f99aXHT/OmuHAgsNq0zKfQ1g6oaXO2PK8MC9EofYxMky6HKf7HNVmBbNrS19O8aVjofzIr1xjlYpLPzpZfrtvVuj1umnwxKYMo8fHdzf1zEijE+fGXK7Y338QQCM0CquTL5ZN1Uc4s3s8iqmQABLhfxZawoiQjgbu4tpBeVMtbAlLyPc1X+RJC/yZfrEoC1ny5fJ1d5sO43UzDkGKPnxbZRZ0tfArKJ4rJ64x69rqgDvw3XH/0J7ErLW4e/T8BAAD//7BCozxRHQAA"; }
        }
    }
}
