// <auto-generated />
namespace Jabbot.TwitterNotifierSprocket.Migrations
{
    using System.Data.Entity.Migrations.Infrastructure;
    
    public sealed partial class First : IMigrationMetadata
    {
        string IMigrationMetadata.Id
        {
            get { return "201112131423552_First"; }
        }
        
        string IMigrationMetadata.Source
        {
            get { return null; }
        }
        
        string IMigrationMetadata.Target
        {
            get { return "H4sIAAAAAAAEAOy9B2AcSZYlJi9tynt/SvVK1+B0oQiAYBMk2JBAEOzBiM3mkuwdaUcjKasqgcplVmVdZhZAzO2dvPfee++999577733ujudTif33/8/XGZkAWz2zkrayZ4hgKrIHz9+fB8/Iv7Hv/cffPx7vFuU6WVeN0W1/Oyj3fHOR2m+nFazYnnx2Ufr9nz74KPf4+g3Th6fzhbv0p807fbQjt5cNp99NG/b1aO7d5vpPF9kzXhRTOuqqc7b8bRa3M1m1d29nZ2Du7s7d3MC8RHBStPHr9bLtljk/Af9eVItp/mqXWflF9UsLxv9nL55zVDTF9kib1bZNP/so+9kk0nVjt9cFW2b1y+qtjgv8vr1qq6mb/N2LAA+So/LIiPkXufl+XtiuvMQmH5kcSAsTgnb9vrN9SpnTD776Ksmr/0W1Ob3yq+DD+ijl3W1yuv2+lV+7r13NvsovRu+e7f7sn218x5Q+Oyjs2V7b++j9MW6LLNJSR+cZ2WTf5SuPn30uq3q/PN8mddZm89eZqARzdfZLOchKCkerT69HTUe3t3ZAzXuZstl1WYtTX4P+Q6qmJ8a+OJPg/HrtiaG+ih9VrzLZ8/z5UU7t1h/kb0zn+zv7BBffbUsiAHprbZe5/4w5e/N3Stf/Nwh8DxrWuHKqdJLMHhKE/KmAEa9edsM8HSJxj7IxsB8UlVlni1vAPn4ruPfjVxNMv5F3mazrM2+DnN/Hcb+/whTs1b5dtbMf7b5afNckZ5ss4LoEDJ7Vwm+yldVUxDRrjvTKFBe562nVoiZXJeiMMes3rok6b7scUsMhs9M0SHawThtf1fUvTELdwfswuMvstWKyO/ZCf0kfS1G4mT79ftr/YXAuDttIsrfYmt7IvpmF3nnW+qaMH1W1E1LAp9NMjDEyWzRa/a1p870789gVzbdZJjW+N3p5xvt57hv4BiwgntGI1+Q8DERlASEWswu6ouvp1mZ1QNW7aQq14vlJgu5CUrH4PjAOl/dHmbPivhQe1/eHm7fOPiA+9/eHnLUSvjAow368B/f7cxxl7c8BaUtOyq/y6m34uNAmXzz7Dxo2Rj+TVy98e2hCeky9vsxtWdwfCDexz/kqetp7W4T27vV3h0t/Vg1ZqDKefxdF7+nQqXJRykR6bKYQX2+vm7afDFGg/HrX1S+zmuKYU7y8T4CE9Psi2xZnOdN+6Z6m5O/wN993bjAOg1NMyv/3xwcFMv2o/RGj+k9fdCoU7+8zOrpPKsjHs/7ucwDPvs3Bn/IJSeBzhGGvjc5Nrjkk6L9/4U7/rPCRp76+qApfj8vue+RDZgkX36HnGJRRcQ7k4oGIQiqG317f/kmdznWyTfhT/c18OO7firm8dO8KS4cCCRmlvkUDO6AmjZny/PKzC+N0sfINOlOv+J/XJPgZNOWvp7mTcOB1E9m5RqjXEzy2dnyy3W7WrfHTZMvJuW1P97Hdzf3z0FDiPPjL1csot/EEAjNAmrjy+WTdVHOLN7PInI+AALsqDJFWFEgSeAuri2kF9XyloCUfE/zVb6ERL7JF6uSgDVfLl9nl/kwbjfTMKTY46dFdlFnC5+C8oli8jqjnr0uqAP/Ddcf/UnsSnnAo/8nAAD//wkMoxd8FAAA"; }
        }
    }
}
