// <auto-generated />
namespace Jabbot.TwitterNotifierSprocket.Migrations
{
    using System.Data.Entity.Migrations;
    using System.Data.Entity.Migrations.Infrastructure;
    
    public sealed partial class AddInviteFields : IMigrationMetadata
    {
        string IMigrationMetadata.Id
        {
            get { return "201112131825515_Add-Invite-Fields"; }
        }
        
        string IMigrationMetadata.Source
        {
            get { return null; }
        }
        
        string IMigrationMetadata.Target
        {
            get { return "H4sIAAAAAAAEAOy9B2AcSZYlJi9tynt/SvVK1+B0oQiAYBMk2JBAEOzBiM3mkuwdaUcjKasqgcplVmVdZhZAzO2dvPfee++999577733ujudTif33/8/XGZkAWz2zkrayZ4hgKrIHz9+fB8/Iv7Hv/cffPx7vFuU6WVeN0W1/Oyj3fHOR2m+nFazYnnx2Ufr9nz74KPf4+g3Th6fzhbv0p807fbQjt5cNp99NG/b1aO7d5vpPF9kzXhRTOuqqc7b8bRa3M1m1d29nZ2Du7s7d3MC8RHBStPHr9bLtljk/Af9eVItp/mqXWflF9UsLxv9nL55zVDTF9kib1bZNP/so+9kk0nVjt9cFW2b1y+qtjgv8vr1qq6mb/N2LAA+So/LIiPkXufl+XtiuvMQmH5kcSAsTgnb9vrN9SpnTD776Ksmr/0W1Ob3yq+DD+ijl3W1yuv2+lV+7r13NvsovRu+e7f7sn218x5Q+Oyjs2V7b++j9MW6LLNJSR+cZ2WTf5SuPn30uq3q/PN8mddZm89eZqARzdfZLOchKCkerT69HTUe3t3ZAzXuZstl1WYtTX4P+Q6qmJ8a+OJPg/HrtiaG+ih9VrzLZ8/z5UU7t1h/kb0zn+zv7BBffbUsiAHprbZe5/4w5e/N3Stf/Nwh8DxrWuHKqdJLMHhKE/KmAEa9edsM8HSJxj7IxsB8UlVlni3fGyRwPJ62xSWzxAfiB2BnSwKVA8QHg3taNGgtEN9zpI/vOkndKL+kzb7I22yWtdnXEeOvI8L/HxFf1p/fzpr5z7bkbJ4rsghtVhAdQrHuqvtX+apqCiLadWcaBcrrvPUUKDGT61JMw5gVeZck3Zc9bonB8JkpOkQ7GGfX7ophMwbw7oAFfPxFtloR+T2LqJ+kr8Ucnmy/fn/7thAYd6dNxMxZbG1PRN/sIu98S10Tps+KumlJ1rNJBoY4mS16zb721Jn+/RnsyqabDNMavztLdKOnMO6bcgas4J7RyBckfEwEJQGhFvMA9MXX06zM6gH7fVKV68Vyky+wCUrHtPrAOl/dHmbPXvpQe1/eHm7fDPqA+9/eHnLUHvrAow1uDz80jl2s3TfvB9G3kF2Y/ne3h9o1lD7U7nd9qI/vdji8K1meetaWHYPXldNbSXGgSr95YR606wz/Jpne+PbQNHTF+v1E2jO3PhDv4x/y1PVsVreJ7d3aro6Neqz2IjBkPP5uKNczINLko5SIdFnMYDxeXzdtvhijwfj1Lypf5zXFqif5eB8BqGn2RbYszvOmfVO9zclb4u++bvxnXaammZX/bw4Ci2X7UXqjv/ieznc0eFteZvV0ntURf+/9QqOB2Owbgz8UepFA50g3vDc5NoRek6J9b3CxsOtr4xYPu742uHjYdfMo/78Rcv2sCIunpD+Ikd8vEup73SGSVrf7Wmoo8BGFS2wzqWgQgqCGSrePiW4KiWKdfBMxU9/OPL7rJxYfP82b4sKBQJpxmU8hxg6oaXO2PK/M/NIofYxMk+70K/7HNamHbNrS19O8aThY/smsXGOUi0k+O1t+uW5X6/a4afLFpAw8x8d3N/fPgWGI8+MvV6yIvokhEJoFNMaXyyfropxZvJ9F5HwABNhRZYqwomQBgbu4tpBeVMtbAlLyPc1X+RIS+SZfrEoC1ny5fJ1d5sO43UzDkGKPnxbZRZ0tfArKJ4rJ64x69rqgDvw3XH/0J7ErZbWP/p8AAAD//xAGcEZKFwAA"; }
        }
    }
}
