// <auto-generated />
namespace Jabbot.TwitterNotifierSprocket.Migrations
{
    using System.Data.Entity.Migrations.Infrastructure;
    
    public sealed partial class AddActivityTime : IMigrationMetadata
    {
        string IMigrationMetadata.Id
        {
            get { return "201112131428159_Add-Activity-Time"; }
        }
        
        string IMigrationMetadata.Source
        {
            get { return null; }
        }
        
        string IMigrationMetadata.Target
        {
            get { return "H4sIAAAAAAAEAOy9B2AcSZYlJi9tynt/SvVK1+B0oQiAYBMk2JBAEOzBiM3mkuwdaUcjKasqgcplVmVdZhZAzO2dvPfee++999577733ujudTif33/8/XGZkAWz2zkrayZ4hgKrIHz9+fB8/Iv7Hv/cffPx7vFuU6WVeN0W1/Oyj3fHOR2m+nFazYnnx2Ufr9nz74KPf4+g3Th6fzhbv0p807fbQjt5cNp99NG/b1aO7d5vpPF9kzXhRTOuqqc7b8bRa3M1m1d29nZ2Du7s7d3MC8RHBStPHr9bLtljk/Af9eVItp/mqXWflF9UsLxv9nL55zVDTF9kib1bZNP/so+9kk0nVjt9cFW2b1y+qtjgv8vr1qq6mb/N2LAA+So/LIiPkXufl+XtiuvMQmH5kcSAsTgnb9vrN9SpnTD776Ksmr/0W1Ob3yq+DD+ijl3W1yuv2+lV+7r13NvsovRu+e7f7sn218x5Q+Oyjs2V7b++j9MW6LLNJSR+cZ2WTf5SuPn30uq3q/PN8mddZm89eZqARzdfZLOchKCkerT69HTUe3t3ZAzXuZstl1WYtTX4P+Q6qmJ8a+OJPg/HrtiaG+ih9VrzLZ8/z5UU7t1h/kb0zn+zv7BBffbUsiAHprbZe5/4w5e/N3Stf/Nwh8DxrWuHKqdJLMHhKE/KmAEa9edsM8HSJxj7IxsB8UlVlni3fGyRwPJ62xSWzxHvh9/iuE4aNIkIK44u8zWZZm30dSfk6UvL/EQlhFfXtrJn/bDPn5rkipdtmBdEhlJyuRn2Vr6qmIKJdd6ZRoLzOW09HEWe6LkX7jllXdknSfdnjlhgMn5miQ7SDcabjrtgOY2PuDhiZx19kqxWR3zM6+kn6WizOyfbr9zchC4Fxd9pELInF1vZE9M0u8s631DVh+qyom5akM5tkYIiT2aLX7GtPnenfn8GubLrJMK3xu1P2Nxrjcd9aMmAF94xGviDhYyIoCQi1mJHVF19PszKrB0zkSVWuF8tN5nYTlI718oF1vro9zJ5J8qH2vrw93L6l8QH3v7095KjJ8YFHG9wefmh/uli7b/oQH9/tcE2XWz2Vpy07RqTL+7eSjEA9ffMCMmgrGf5NcrLx7aEp6IrK+4mJZ8J8IN7HP+Sp69mBbhPbu7UHHb3/WHVwYBx4/N0IpKeUpclHKRHpsphBIb++btp8MUaD8etfVL7OawqxTvLxPuIm0+yLbFmc5037pnqbkwfC333dsMW6IU0zK//fHLsUy/aj9EYf7D392WjMsbzM6uk8qyM+1Pt59AMhxTcGfyhiIIHOESW/Nzk2RAyTon1vcLFo4Za4/X8jWvhZ4UlPF34Qv7yfE993GAfsm68Mhnx20Ws02ZOKBiEIqpd/e3f+Jm8+1sk34e731fnju37a6fHTvCkuHAgkoZb5FNLigJo2Z8vzyswvjdLHyDTpTr/if1yTFGbTlr6e5k3Dcd5PZuUao1xM8tnZ8st1u1q3x02TLyZl4PQ8vru5f45pQpwff7lief8mhkBoFpDzL5dP1kU5s3g/i8j5AAiwo8oUYUVxLoG7uLaQXlTLWwJS8j3NV/kSEvkmX6xKAtZ8uXydXebDuN1Mw5Bij58W2UWdLXwKyieKyeuMeva6oA78N1x/9CexK+U8j/6fAAAA//9057ixaBUAAA=="; }
        }
    }
}
